spring.application.name=Nayra-Backend

spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/nayra
spring.datasource.username=postgres
spring.datasource.password=postgre
