-- D-052: esquema inicial versionado. Tablas y columnas de usuarios y roles tomadas del código inicial,
-- con nombres alineados a 03_BASE_DE_DATOS_NAYRA.md (usuarios, roles).

CREATE TABLE usuarios (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          VARCHAR(30)  NOT NULL UNIQUE,
    -- Pendiente P-A01 (autenticación del personal y del administrador). No se usa para usuarios de la app.
    password          VARCHAR(200),
    enabled           BOOLEAN      NOT NULL,
    dni               VARCHAR(12)  NOT NULL UNIQUE,
    email             VARCHAR(100) NOT NULL UNIQUE,
    fecha_nacimiento  DATE         NOT NULL,
    telefono          VARCHAR(20)  NOT NULL,
    direccion         VARCHAR(150),
    foto_usuario      VARCHAR(255),
    -- D-043 / D-047
    pin_hash          VARCHAR(255),
    intentos_fallidos INTEGER      NOT NULL DEFAULT 0,
    bloqueado         BOOLEAN      NOT NULL DEFAULT FALSE,
    fecha_bloqueo     TIMESTAMP WITH TIME ZONE
);

CREATE TABLE roles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol        VARCHAR(30) NOT NULL,
    usuario_id BIGINT      NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT uk_roles_usuario_rol UNIQUE (usuario_id, rol)
);
