-- D-041: dispositivos con clave pública; un único dispositivo ACTIVO por usuario.
CREATE TABLE dispositivos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_publico       UUID         NOT NULL UNIQUE,
    usuario_id       BIGINT       NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    plataforma       VARCHAR(30)  NOT NULL CHECK (plataforma IN ('ANDROID', 'IOS')),
    nombre           VARCHAR(100),
    clave_publica    TEXT         NOT NULL,
    algoritmo        VARCHAR(30)  NOT NULL,
    estado           VARCHAR(20)  NOT NULL CHECK (estado IN ('ACTIVO', 'REVOCADO')),
    fecha_registro   TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_revocacion TIMESTAMP WITH TIME ZONE
);
CREATE UNIQUE INDEX uk_dispositivos_activo_por_usuario ON dispositivos (usuario_id) WHERE estado = 'ACTIVO';

-- D-042: sesiones con token opaco; solo se guarda el hash SHA-256.
CREATE TABLE sesiones (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_publico     UUID      NOT NULL UNIQUE,
    usuario_id     BIGINT    NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    dispositivo_id BIGINT    REFERENCES dispositivos (id) ON DELETE SET NULL,
    token_hash     VARCHAR(64) NOT NULL UNIQUE,
    fecha_inicio   TIMESTAMP WITH TIME ZONE NOT NULL,
    ultimo_acceso  TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_cierre   TIMESTAMP WITH TIME ZONE,
    motivo_cierre  VARCHAR(30)
);
CREATE INDEX ix_sesiones_usuario_abiertas ON sesiones (usuario_id) WHERE fecha_cierre IS NULL;

-- D-037 / D-048: desafíos y nonces de un solo uso, persistidos para funcionar con 2 instancias (D-023).
CREATE TABLE desafios_autenticacion (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_publico       UUID        NOT NULL UNIQUE,
    usuario_id       BIGINT      REFERENCES usuarios (id) ON DELETE CASCADE,
    dispositivo_id   BIGINT      REFERENCES dispositivos (id) ON DELETE CASCADE,
    proposito        VARCHAR(30) NOT NULL CHECK (proposito IN ('LOGIN', 'REGISTRO_DISPOSITIVO', 'REAUTENTICACION')),
    elementos        VARCHAR(200),
    nonce            VARCHAR(64) NOT NULL UNIQUE,
    fecha_emision    TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_expiracion TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_uso        TIMESTAMP WITH TIME ZONE
);
